# Generated by Django 2.2.7 on 2020-04-03 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('startTime', models.DateTimeField()),
                ('interval', models.IntegerField()),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=1000)),
                ('sender', models.CharField(max_length=100)),
                ('recvTime', models.DateTimeField(auto_now=True)),
                ('sessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofSession', to='LiveStreamApp.Session')),
            ],
        ),
    ]
