# Generated by Django 2.2.7 on 2020-04-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveStreamApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
