# Generated by Django 2.2.7 on 2020-04-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LiveStreamApp', '0002_session_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('clss', models.CharField(max_length=10)),
                ('roll', models.IntegerField()),
                ('mob', models.CharField(max_length=12)),
                ('who', models.CharField(max_length=10)),
                ('login', models.DateTimeField(auto_now=True)),
                ('logout', models.DateTimeField()),
                ('sessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_inSessId', to='LiveStreamApp.Session')),
            ],
        ),
    ]
