# Generated by Django 2.2.7 on 2020-04-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveStreamApp', '0003_peer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='roll',
        ),
        migrations.AlterField(
            model_name='peer',
            name='clss',
            field=models.CharField(default='', max_length=20),
        ),
    ]
