# Generated by Django 2.2.7 on 2020-04-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LiveStreamApp', '0004_auto_20200406_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='sessId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_inSess', to='LiveStreamApp.Session'),
        ),
    ]
