# Generated by Django 2.2.7 on 2020-04-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LiveStreamApp', '0005_auto_20200406_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sessId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ofSession', to='LiveStreamApp.Session'),
        ),
    ]
