# Generated by Django 2.2.7 on 2020-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveStreamApp', '0006_auto_20200406_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peer',
            old_name='sessId',
            new_name='sess',
        ),
        migrations.AlterField(
            model_name='peer',
            name='mob',
            field=models.CharField(max_length=10),
        ),
    ]
