# Generated by Django 2.2.7 on 2020-04-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveStreamApp', '0007_auto_20200406_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='logout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
