# Generated by Django 2.2.7 on 2020-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveStreamApp', '0008_auto_20200406_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='section',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='peer',
            name='clss',
            field=models.CharField(default='', max_length=10),
        ),
    ]
