# Generated by Django 2.2.7 on 2020-04-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveStreamApp', '0009_auto_20200407_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
