# Generated by Django 2.2.7 on 2020-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveStreamApp', '0010_auto_20200407_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='login',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='peer',
            name='logout',
            field=models.DateTimeField(),
        ),
    ]
